title = "jreminder config file"

[log]
level = "info"
report_caller = false

[holiday]
path = "XXX"

[github]
token = "XXX"

[account]
email = "XXX"
password = "XXX"

[repositories]
[repositories.bitxhub]
repository = "meshplus"
project = "bitxhub"
rules = ["checkMainBranchMerged.rule1", "checkPullRequestTimeout.rule1"]
webhook = ["dingtalk"]

[repositories.pier]
repository = "meshplus"
project = "pier"
rules = ["checkMainBranchMerged.rule1", "checkPullRequestTimeout.rule1"]
webhook = ["dingtalk"]

[teambition]
[teambition.bitxhub]
project = "XXX"
app = "XXX"
rules = ["checkTeambitionTimeout.rule1"]
webhook = ["dingtalk"]

[rules]
# check if the main branches are merged
[rules.checkMainBranchMerged.rule1]
base = "master"
head = "release*"
cron = "0 30 16 * * *"
# check if the pull request timed out
[rules.checkPullRequestTimeout.rule1]
timeout = "72h"
cron = "0 30 16 * * *"
# check if the task timed out
[rules.checkTeambitionTimeout.rule1]
cron = "0 30 16 * * *"

[members]
[members.XXX]
github = "XXX"
name = "XXX"
phone = "XXX"

[webhooks]
[webhook.dingtalk]
webhook = "XXX"
