title = "jreminder config file"

[log]
level = "info"

[github]
token = "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"

[repositories]
[repositories.bitxhub]
repository = "meshplus"
project = "bitxhub"
rules = ["checkMainBranchMerged.rule1", "checkPullRequestTimeout.rule1"]
webhook = ["dingtalk"]

[repositories.pier]
repository = "meshplus"
project = "pier"
rules = ["checkMainBranchMerged.rule1", "checkPullRequestTimeout.rule1"]
webhook = ["dingtalk"]

[rules]
# check if the main branches are merged
[rules.checkMainBranchMerged.rule1]
base = "master"
head = "release*"
cron = "0 30 16 * * *"
# check if the pull request timed out
[rules.checkPullRequestTimeout.rule1]
timeout = "72h"
cron = "0 30 16 * * *"

[members]
[members.jiuhuche120]
phone = "17376591745"

[members.levi9311]
phone = "18868105086"

[members.Karenlrx]
phone = "18328369578"

[members.peterzhuzhuzhuz]
phone = "13328400820"

[members.xiaochenl]
phone = "18248455158"

[members.johnsonwyj]
phone = "13819149972"

[members.99MyCql]
phone = "15651023329"

[members.pigxiaolei]
phone = "15979182656"

[webhooks]
[webhook.dingtalk]
webhook = "https://oapi.dingtalk.com/robot/send?access_token=89240674ce78edb5f96b7d8607a3516b81ab55ce7cb60aa9c9551dabefefbf49"
